<?php

    namespace Modules\Cultural\Controllers;
    use App\Http\Controllers\Controller;
    use Modules\Cultural\Models\Cultural;
    use Illuminate\Http\Request;
    use Modules\Cultural\Models\CulturalCategory;
    use Modules\Location\Models\Location;
    use Modules\Review\Models\Review;
    use Modules\Core\Models\Attributes;
    use DB;

    class CulturalController extends Controller
    {
        protected $culturalClass;
        protected $locationClass;
        protected $culturalCategoryClass;
        protected $attributesClass;

        public function __construct(Cultural $cultural)
        {
            $this->culturalClass = $cultural;
            $this->locationClass = Location::class;
            $this->culturalCategoryClass = CulturalCategory::class;
            $this->attributesClass = Attributes::class;
        }
        public function callAction($method, $parameters)
        {
            if(setting_item('cultural_disable'))
            {
                return redirect('/');
            }
            return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
        }

        public function index(Request $request)
        {
            $is_ajax = $request->query('_ajax');

            if(!empty($request->query('limit'))){
                $limit = $request->query('limit');
            }else{
                $limit = !empty(setting_item("cultural_page_limit_item"))? setting_item("cultural_page_limit_item") : 9;
            }
            $query = $this->culturalClass->search($request->input());
            $list = $query->paginate($limit);

            $markers = [];
            if (!empty($list)) {
                foreach ($list as $row) {
                    $markers[] = [
                        "id" => $row->id,
                        "title" => $row->title,
                        "lat" => (float)$row->map_lat,
                        "lng" => (float)$row->map_lng,
                        "gallery" => $row->getGallery(true),
                        "infobox" => view('Cultural::frontend.layouts.search.loop-grid', ['row' => $row, 'disable_lazyload' => 1, 'wrap_class' => 'infobox-item'])->render(),
                        'marker' => get_file_url(setting_item("cultural_icon_marker_map"),'full') ?? url('images/icons/png/pin.png'),
                    ];
                }
            }
            $limit_location = 15;
            if( empty(setting_item("space_location_search_style")) or setting_item("space_location_search_style") == "normal" ){
                $limit_location = 1000;
            }
            $data = [
                'rows' => $list,
                'cultural_category' => $this->culturalCategoryClass::where('status', 'publish')->with(['translation'])->get()->toTree(),
                'cultural_location' => $this->locationClass::where('status', 'publish')->with(['translation'])->limit($limit_location)->get()->toTree(),
                'cultural_min_max_price' => $this->culturalClass::getMinMaxPrice(),
                'markers' => $markers,
                "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1 ,
                "seo_meta" => $this->culturalClass::getSeoMetaForPageList()
            ];
            $layout = setting_item("cultural_layout_search", 'normal');
            if ($request->query('_layout')) {
                $layout = $request->query('_layout');
            }
            $data['layout'] = $layout;
            if ($is_ajax) {
                return $this->sendSuccess([
                    'html' => view('Cultural::frontend.layouts.search-map.list-item', $data)->render(),
                    "markers" => $data['markers']
                ]);
            }
            $data['attributes'] = $this->attributesClass::where('service', 'cultural')->orderBy("position","desc")->with(['terms','translation'])->get();
            if ($layout == "map") {
                $data['body_class'] = 'has-search-map';
                $data['html_class'] = 'full-page';
                return view('Cultural::frontend.search-map', $data);
            }
            return view('Cultural::frontend.search', $data);
        }

        public function detail(Request $request, $slug)
        {
            $row = $this->culturalClass::where('slug', $slug)->with(['location','translation','hasWishList'])->first();
            if ( empty($row) or !$row->hasPermissionDetailView()) {
                return redirect('/');
            }
            if (!empty($request['preview_panorama'])) {
                return view_panorama($row);
            }
            $translation = $row->translate();
            $cultural_related = [];
            $location_id = $row->location_id;
            if (!empty($location_id)) {
                $cultural_related = $this->culturalClass::where('location_id', $location_id)->where("status","publish")->take(4)->whereNotIn('id', [$row->id])->with(['location','translation','hasWishList'])->get();
            }
            $review_list = $row->getReviewList();

            $data = [
                'row' => $row,
                'translation' => $translation,
                'cultural_related' => $cultural_related,
                'booking_data' => $row->getBookingData(),
                'review_list' => $review_list,
                'seo_meta' => $row->getSeoMetaWithTranslation(app()->getLocale(), $translation),
                'body_class'=>'is_single',
                'breadcrumbs'       => [
                    [
                        'name'  => __('Cultural'),
                        'url'  => route('cultural.search'),
                    ],
                ],
            ];
            $data['breadcrumbs'] = array_merge($data['breadcrumbs'],$row->locationBreadcrumbs());
            $data['breadcrumbs'][] = [
                'name'  => $translation->title,
                'class' => 'active'
            ];
            $this->setActiveMenu($row);
            return view('Cultural::frontend.detail', $data);

        }
    }
