<?php
namespace Modules\Cultural\Controllers;

use App\Http\Controllers\Controller;
use Modules\Cultural\Models\Cultural;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Location\Models\LocationCategory;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use App\Models\Ipanorama;
use App\Models\RefRelationIpanorama;
use App\Models\RefIpanorama;
use DB;

class CulturalController extends Controller
{
    protected $culturalClass;
    protected $locationClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct(Cultural $culturalClass, Location $locationClass,LocationCategory $locationCategoryClass)
    {
        $this->culturalClass = $culturalClass;
        $this->locationClass = $locationClass;
        $this->locationCategoryClass = $locationCategoryClass;
    }

    public function callAction($method, $parameters)
    {
        if(!$this->culturalClass::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request)
    {
        $is_ajax = $request->query('_ajax');

        if(!empty($request->query('limit'))){
            $limit = $request->query('limit');
        }else{
            $limit = !empty(setting_item("cultural_page_limit_item"))? setting_item("cultural_page_limit_item") : 9;
        }

        $query = $this->culturalClass->search($request->input());
        $list = $query->paginate($limit);

        $markers = [];
        if (!empty($list)) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Cultural::frontend.layouts.search.loop-grid', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item("cultural_icon_marker_map"),'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if( empty(setting_item("cultural_location_search_style")) or setting_item("cultural_location_search_style") == "normal" ){
            $limit_location = 1000;
        }
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translation'])->get()->toTree(),
            'cultural_min_max_price' => $this->culturalClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1 ,
            "seo_meta"           => $this->culturalClass::getSeoMetaForPageList()
        ];
        $layout = setting_item("cultural_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        $data['layout'] = $layout;
        if ($is_ajax) {
            return $this->sendSuccess([
                'html'    => view('Cultural::frontend.layouts.search-map.list-item', $data)->render(),
                "markers" => $data['markers']
            ]);
        }
        $data['attributes'] = Attributes::where('service', 'cultural')->orderBy("position","desc")->with(['terms','translation'])->get();

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Cultural::frontend.search-map', $data);
        }
        return view('Cultural::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->culturalClass::where('slug', $slug)->with(['location','translation','hasWishList'])->first();;
        if ( empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translate();
        $cultural_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $cultural_related = $this->culturalClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location','translation','hasWishList'])->get();
        }
        $review_list = $row->getReviewList();

        $dataIpanorama = RefRelationIpanorama::where('slug', $slug)
        ->join('ref_add_ipanorama', 'ref_relation_ipanorama.id_ipanorama', '=', 'ref_add_ipanorama.id')
        ->first();

        if($dataIpanorama) {
            $dataIpanorama = $dataIpanorama->code;
        }else{
            $dataIpanorama = null;
        }

        $data = [
            'row'          => $row,
            'translation'       => $translation,
            'ipanorama' => $dataIpanorama,
            'cultural_related' => $cultural_related,
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->with('location_category_translations')->get(),
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single',
            'breadcrumbs'       => [
                [
                    'name'  => 'Cultural',
                    'url'  => route('cultural.search'),
                ],
            ],
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'],$row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name'  => $translation->title,
            'class' => 'active'
        ];
        $this->setActiveMenu($row);
        // return view('Cultural::frontend.detail', $data);
        return view('Cultural::frontend.detail', ['data' => $data, 'row' => $row, 'translation' => $data['translation'], 'cultural_related' => $data['cultural_related'], 'ipanorama' => $data['ipanorama'], 'booking_data' => $data['booking_data'], 'review_list' => $data['review_list'], 'seo_meta' => $data['seo_meta'], 'body_class' => $data['body_class'], 'breadcrumbs' => $data['breadcrumbs'] ]);
    }
}
