<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 7/30/2019
 * Time: 1:56 PM
 */
namespace Modules\Cultural\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Cultural\Models\Cultural;
use Modules\Cultural\Models\CulturalTerm;
use Modules\Cultural\Models\CulturalTranslation;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;
use Modules\Location\Models\LocationCategory;
use App\Models\Ipanorama;
use App\Models\RefIpanorama;
use App\Models\RefRelationIpanorama;
use App\Models\CategoryProduct;
use App\Models\SubscribeVirtuard;
use App\Models\ProductCategory;

class CulturalController extends AdminController
{
    protected $cultural;
    protected $cultural_translation;
    protected $cultural_term;
    protected $attributes;
    protected $location;
    private $locationCategoryClass;

    public function __construct(Cultural $cultural, CulturalTranslation $cultural_translation, CulturalTerm $cultural_term, Attributes $attributes, Location $location,LocationCategory $locationCategoryClass)
    {
        $this->setActiveMenu(route('cultural.admin.index'));
        $this->cultural = $cultural;
        $this->cultural_translation = $cultural_translation;
        $this->cultural_term = $cultural_term;
        $this->attributes = $attributes;
        $this->location = $location;
        $this->locationCategoryClass = $locationCategoryClass;
    }

    public function callAction($method, $parameters)
    {
        if (!Cultural::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('cultural_view');
        $query = $this->cultural::query();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if (!empty($is_featured = $request->input('is_featured'))) {
            $query->where('is_featured', 1);
        }
        if (!empty($location_id = $request->query('location_id'))) {
            $query->where('location_id', $location_id);
        }
        if ($this->hasPermission('cultural_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('author_id', $author);
            }
        } else {
            $query->where('author_id', Auth::id());
        }
        $data = [
            'rows'                => $query->with(['author'])->paginate(20),
            'cultural_manage_others' => $this->hasPermission('cultural_manage_others'),
            'breadcrumbs'         => [
                [
                    'name' => __('Culturals'),
                    'url'  => route('cultural.admin.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'          => __("Cultural Management")
        ];
        return view('Cultural::admin.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('cultural_view');
        $query = $this->cultural::onlyTrashed();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('cultural_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('author_id', $author);
            }
        } else {
            $query->where('author_id', Auth::id());
        }
        $data = [
            'rows'                => $query->with(['author'])->paginate(20),
            'cultural_manage_others' => $this->hasPermission('cultural_manage_others'),
            'recovery'            => 1,
            'breadcrumbs'         => [
                [
                    'name' => __('Culturals'),
                    'url'  => route('cultural.admin.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'          => __("Recovery Cultural Management")
        ];
        return view('Cultural::admin.index', $data);
    }

    public function create(Request $request)
    {
        $idUser = Auth::id();
        $dataIpanorama = RefIpanorama::where('id_user', $idUser)->get();
        $categories = ProductCategory::where('type', 'cultural')->get();

        $isVirtuard360 = $this->checkVirtuard360();
        $this->checkPermission('cultural_create');
        $row = new $this->cultural();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'               => $row,
            'attributes'        => $this->attributes::where('service', 'cultural')->get(),
            'cultural_location'    => $this->location::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'translation'       => new $this->cultural_translation(),
            'breadcrumbs'       => [
                [
                    'name' => __('Culturals'),
                    'url'  => route('cultural.admin.index')
                ],
                [
                    'name'  => __('Add Cultural'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Add new Cultural")
        ];
        // return view('Cultural::admin.detail', $data);
        return view('Cultural::admin.detail', ['data' => $data, 'isVirtuard360' => $isVirtuard360, 'dataIpanorama' => $dataIpanorama, 'row' => $row, 'translation' => $data['translation'], 'location_category' => $data['location_category'], 'attributes' => $data['attributes'], 'breadcrumbs' => $data['breadcrumbs'], 'cultural_location' => $data['cultural_location'], 'categories' => $categories, ]);
    }

    public function edit(Request $request, $id)
    {
        $idUser = Auth::id();
        $dataIpanorama = RefIpanorama::where('id_user', $idUser)->get();

        $isVirtuard360 = $this->checkVirtuard360();
        $this->checkPermission('cultural_update');
        $row = $this->cultural::find($id);
        if (empty($row)) {
            return redirect(route('cultural.admin.index'));
        }
        $translation = $row->translate($request->query('lang',get_main_lang()));
        if (!$this->hasPermission('cultural_manage_others')) {
            if ($row->author_id != Auth::id()) {
                return redirect(route('cultural.admin.index'));
            }
        }
        $data = [
            'row'               => $row,
            'translation'       => $translation,
            "selected_terms"    => $row->terms->pluck('term_id'),
            'attributes'        => $this->attributes::where('service', 'cultural')->get(),
            'cultural_location'    => $this->location::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'enable_multi_lang' => true,
            'breadcrumbs'       => [
                [
                    'name' => __('Culturals'),
                    'url'  => route('cultural.admin.index')
                ],
                [
                    'name'  => __('Edit Cultural'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Edit: :name", ['name' => $row->title])
        ];
        // return view('Cultural::admin.detail', $data);
        return view('Cultural::admin.detail', ['data' => $data, 'isVirtuard360' => $isVirtuard360, 'dataIpanorama' => $dataIpanorama, 'row' => $row, 'translation' => $data['translation'], 'selected_terms' => $data['selected_terms'], 'attributes' => $data['attributes'], 'breadcrumbs' => $data['breadcrumbs'], 'cultural_location' => $data['cultural_location'], 'location_category' => $data['location_category'], 'enable_multi_lang' => $data['enable_multi_lang'] ]);
    }

    public function store(Request $request, $id)
    {

        if ($id > 0) {
            $this->checkPermission('cultural_update');
            $row = $this->cultural::find($id);
            if (empty($row)) {
                return redirect(route('cultural.admin.index'));
            }
            if ($row->author_id != Auth::id() and !$this->hasPermission('cultural_manage_others')) {
                return redirect(route('cultural.admin.index'));
            }
        } else {
            $this->checkPermission('cultural_create');
            $row = new $this->cultural();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'status',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'duration',
            'start_time',
            'price',
            'sale_price',
            'ticket_types',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'surrounding',
            'end_time',
            'duration_unit',
        ];
        if ($this->hasPermission('cultural_manage_others')) {
            $dataKeys[] = 'author_id';
        }
        $row->fillByAttr($dataKeys, $request->input());
        if ($request->input('slug')) {
            $row->slug = $request->input('slug');
        }

        if($request->file('image-ipanorama-1')) {
            $dataIpanorama = array();

            $proofImage1 = $request->file('image-ipanorama-1');
            $proofImage2 = $request->file('image-ipanorama-2');
            $proofImage3 = $request->file('image-ipanorama-3');
            $proofImage4 = $request->file('image-ipanorama-4');

            $path1 = $proofImage1->store('public/images/ipanorama');
            $path2 = $proofImage2->store('public/images/ipanorama');
            $path3 = $proofImage3->store('public/images/ipanorama');
            $path4 = $proofImage4->store('public/images/ipanorama');

            array_push($dataIpanorama, $path1);
            array_push($dataIpanorama, $path2);
            array_push($dataIpanorama, $path3);
            array_push($dataIpanorama, $path4);

            $dataIpanoramaString = implode(', ', $dataIpanorama);
        }

        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            if ($id > 0) {
                event(new UpdatedServiceEvent($row));

                $ipanoramaInp = RefRelationIpanorama::where('slug', '=', $row->slug)->first();

                if ($ipanoramaInp) {
                    $ipanoramaInp->id_ipanorama = $request->input('div-ipanorama');
                    $ipanoramaInp->save();
                } else {
                    $ipanoramaInpNew = new RefRelationIpanorama();
                    $ipanoramaInpNew->id_ipanorama = $request->input('div-ipanorama');
                    $ipanoramaInpNew->slug = $row->slug;
                    $ipanoramaInpNew->save();
                }

                return back()->with('success', __('Cultural updated'));
            } else {
                event(new CreatedServicesEvent($row));

                $ipanoramaInp = new RefRelationIpanorama();
                $ipanoramaInp->id_ipanorama = $request->input('div-ipanorama');
                $ipanoramaInp->slug = $row->slug;
                $ipanoramaInp->save();

                return redirect(route('cultural.admin.edit', $row->id))->with('success', __('Cultural created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('cultural_manage_attributes');
        if (empty($request->input('terms'))) {
            $this->cultural_term::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->cultural_term::firstOrCreate([
                    'term_id'   => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->cultural_term::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function bulkEdit(Request $request)
    {

        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->cultural::where("id", $id);
                    if (!$this->hasPermission('cultural_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('cultural_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->delete();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "permanently_delete":
                foreach ($ids as $id) {
                    $query = $this->cultural::where("id", $id);
                    if (!$this->hasPermission('cultural_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('cultural_delete');
                    }
                    $row = $query->withTrashed()->first();
                    if ($row) {
                        $row->forceDelete();
                    }
                }
                return redirect()->back()->with('success', __('Permanently delete success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->cultural::withTrashed()->where("id", $id);
                    if (!$this->hasPermission('cultural_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('cultural_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->restore();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('cultural_create');
                foreach ($ids as $id) {
                    (new $this->cultural())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->cultural::where("id", $id);
                    if (!$this->hasPermission('cultural_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('cultural_update');
                    }
                    $row = $query->first();
                    $row->status = $action;
                    $row->save();
                    event(new UpdatedServiceEvent($row));
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }

    public function getForSelect2(Request $request)
    {
        $pre_selected = $request->query('pre_selected');
        $selected = $request->query('selected');
        if ($pre_selected && $selected) {
            if (is_array($selected)) {
                $items = $this->cultural::select('id', 'title as text')->whereIn('id', $selected)->take(50)->get();
                return $this->sendSuccess([
                    'items' => $items
                ]);
            } else {
                $item = $this->cultural::find($selected);
            }
            if (empty($item)) {
                return $this->sendSuccess([
                    'text' => ''
                ]);
            } else {
                return $this->sendSuccess([
                    'text' => $item->name
                ]);
            }
        }
        $q = $request->query('q');
        $query = $this->cultural::select('id', 'title as text')->where("status", "publish");
        if ($q) {
            $query->where('title', 'like', '%' . $q . '%');
        }
        $res = $query->orderBy('id', 'desc')->limit(20)->get();
        return $this->sendSuccess([
            'results' => $res
        ]);
    }
}
