<?php
namespace Modules\Business\Controllers;

use App\Http\Controllers\Controller;
use Modules\Location\Models\LocationCategory;
use Modules\Business\Models\Business;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use App\Models\Ipanorama;
use App\Models\RefRelationIpanorama;
use App\Models\RefIpanorama;
use DB;
use Modules\Business\Models\BusinessCategory;

class BusinessController extends Controller
{
    protected $businessClass;
    protected $locationClass;
    protected $businessCategoryClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct(Business $businessClass)
    {
        $this->businessClass = $businessClass;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->businessCategoryClass = BusinessCategory::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Business::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {

        $is_ajax = $request->query('_ajax');
        if(!empty($request->query('limit'))){
            $limit = $request->query('limit');
        }else{
            $limit = !empty(setting_item("business_page_limit_item"))? setting_item("business_page_limit_item") : 9;
        }
        
        $query = $this->businessClass->search($request->input());
        $list = $query->paginate($limit);
        $markers = [];
        if (!empty($list)) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Business::frontend.layouts.search.loop-grid', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item("business_icon_marker_map"),'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if( empty(setting_item("business_location_search_style")) or setting_item("business_location_search_style") == "normal" ){
            $limit_location = 1000;
        }
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translation'])->get()->toTree(),
            'business_min_max_price' => $this->businessClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1 ,
            "seo_meta"           => $this->businessClass::getSeoMetaForPageList()
        ];
        $layout = setting_item("business_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        if ($is_ajax) {
            return $this->sendSuccess([
                'html'    => view('Business::frontend.layouts.search-map.list-item', $data)->render(),
                "markers" => $data['markers']
            ]);
        }
        $data['attributes'] = Attributes::where('service', 'business')->orderBy("position","desc")->with(['terms','translation'])->get();
        $data['layout'] = $layout;

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Business::frontend.search-map', $data);
        }
        return view('Business::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->businessClass::where('slug', $slug)->with(['location','translation','hasWishList'])->first();
        if ( empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translate();
        $business_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $business_related = $this->businessClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location','translation','hasWishList'])->get();
        }
        $review_list = $row->getReviewList();
        
        $dataIpanorama = RefRelationIpanorama::where('slug', $slug)
        ->join('ref_add_ipanorama', 'ref_relation_ipanorama.id_ipanorama', '=', 'ref_add_ipanorama.id')
        ->first();

        if($dataIpanorama) {
            $dataIpanorama = $dataIpanorama->code;
        }else{
            $dataIpanorama = null;
        }

        $data = [
            'row'          => $row,
            'translation'       => $translation,
            'business_related' => $business_related,
            'ipanorama' => $dataIpanorama,
            'business_category'     => $this->businessCategoryClass::where('status', 'publish')->get()->toTree(),
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->with('location_category_translations')->get(),
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single',
            'breadcrumbs'       => [
                [
                    'name'  => __('Business'),
                    'url'  => route('business.search'),
                ],
            ],
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'],$row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name'  => $translation->title,
            'class' => 'active'
        ];
        $this->setActiveMenu($row);
        return view('Business::frontend.detail', $data);
    }
}
