<?php
namespace Modules\Business\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\LocationCategory;
use Modules\Business\Models\Business;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;
use Modules\Business\Models\BusinessCategory;
use Modules\Business\Models\BusinessTerm;
use Modules\Business\Models\BusinessTranslation;
use Modules\User\Models\Plan;

class ManageBusinessController extends FrontendController
{
    protected $businessClass;
    protected $businessTranslationClass;
    protected $businessTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    protected $businessCategoryClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct()
    {
        parent::__construct();
        $this->businessClass = Business::class;
        $this->businessTranslationClass = BusinessTranslation::class;
        $this->businessTermClass = BusinessTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->bookingClass = Booking::class;
        $this->businessCategoryClass = BusinessCategory::class;
    }
    public function callAction($method, $parameters)
    {
        if(!Business::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function manageBusiness(Request $request)
    {
        $this->checkPermission('business_view');
        $user_id = Auth::id();
        $rows = $this->businessClass::where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $rows->paginate(5),
            'breadcrumbs'        => [
                [
                    'name' => __('listing.business.manage'),
                    'url'  => route('business.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("listing.business.manage"),
        ];
        return view('Business::frontend.manageBusiness.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('business_view');
        $user_id = Auth::id();
        $rows = $this->businessClass::onlyTrashed()->where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $rows->paginate(5),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('listing.business.manage'),
                    'url'  => route('business.vendor.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Recovery Business"),
        ];
        return view('Business::frontend.manageBusiness.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('business_delete');
        $user_id = Auth::id();
        $query = $this->businessClass::onlyTrashed()->where("author_id", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
            event(new UpdatedServiceEvent($query));

        }
        return redirect(route('business.vendor.recovery'))->with('success', __('Restore business success!'));
    }

    public function createBusiness(Request $request)
    {
        $this->checkPermission('business_create');
        $row = new $this->businessClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->businessTranslationClass(),
            'business_category'     => $this->businessCategoryClass::where('status', 'publish')->get()->toTree(),
            'business_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes'    => $this->attributesClass::where('service', 'business')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('listing.business.manage'),
                    'url'  => route('business.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Business"),
        ];
        return view('Business::frontend.manageBusiness.detail', $data);
    }


    public function store( Request $request, $id ){

        if($id>0){
            $this->checkPermission('business_update');
            $row = $this->businessClass::find($id);
            if (empty($row)) {
                return redirect(route('business.vendor.index'));
            }

            if($row->author_id != Auth::id() and !$this->hasPermission('business_manage_others'))
            {
                return redirect(route('business.vendor.index'));
            }
        }else{
            $this->checkPermission('business_create');
            $row = new $this->businessClass();
            $row->status = "publish";
            if(setting_item("business_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
            $row->author_id = Auth::id();
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'bed',
            'bathroom',
            'square',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'default_state',
            'price',
            'sale_price',
            'max_guests',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'min_day_before_booking',
            'min_day_stays',
            'enable_service_fee',
            'service_fee',
            'surrounding',
            'franchising',
            'phone',
            'website',
            'ipanorama_id',

        ];
        $row->fillByAttr($dataKeys,$request->input());
        if(!auth()->user()->checkUserPlan() and $row->status == "publish") {
            return redirect(route('user.plan'));
        }
	    $row->ical_import_url  = $request->ical_import_url;
        $res = $row->saveOriginOrTranslation($request->input('lang'),true);
        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if($id > 0 ){
                event(new UpdatedServiceEvent($row));
                return back()->with('success',  __('Business updated') );
            }else{
                event(new CreatedServicesEvent($row));
                return redirect(route('business.vendor.edit',['id'=>$row->id]))->with('success', __('Business created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->businessTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->businessTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->businessTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function editBusiness(Request $request, $id)
    {
        $this->checkPermission('business_update');
        $user_id = Auth::id();
        $row = $this->businessClass::where("author_id", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('business.vendor.index'))->with('warning', __('Business not found!'));
        }
        $translation = $row->translate($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'business_category'     => $this->businessCategoryClass::where('status', 'publish')->get()->toTree(),
            'business_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes'    => $this->attributesClass::where('service', 'business')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('listing.business.manage'),
                    'url'  => route('business.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Business"),
        ];
        return view('Business::frontend.manageBusiness.detail', $data);
    }

    public function deleteBusiness($id)
    {
        $this->checkPermission('business_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->businessClass::where("author_id", $user_id)->where("id", $id)->withTrashed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->businessClass::where("author_id", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
                event(new UpdatedServiceEvent($query));
            }
        }
        return redirect(route('business.vendor.index'))->with('success', __('Delete business success!'));
    }

    public function bulkEditBusiness($id , Request $request){
        $this->checkPermission('business_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->businessClass::where("author_id", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                if(!auth()->user()->checkUserPlan()) {
                    return redirect(route('user.plan'));
                }
                break;
            case 'make-private':
                $query->status = 'private';
                break;
        }
        $query->save();
        event(new UpdatedServiceEvent($query));

        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("business_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();

                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }

	public function cloneBusiness(Request $request,$id){
		$this->checkPermission('business_update');
		$user_id = Auth::id();
		$row = $this->businessClass::where("author_id", $user_id);
		$row = $row->find($id);
		if (empty($row)) {
			return redirect(route('business.vendor.index'))->with('warning', __('Business not found!'));
		}
		try{
			$clone = $row->replicate();
			$clone->status  = 'draft';
			$clone->push();
			if(!empty($row->terms)){
				foreach ($row->terms as $term){
					$e= $term->replicate();
					if($e->push()){
						$clone->terms()->save($e);

					}
				}
			}
			if(!empty($row->meta)){
				$e= $row->meta->replicate();
				if($e->push()){
					$clone->meta()->save($e);

				}
			}
			if(!empty($row->translations)){
				foreach ($row->translations as $translation){
					$e = $translation->replicate();
					$e->origin_id = $clone->id;
					if($e->push()){
						$clone->translations()->save($e);
					}
				}
			}

			return redirect()->back()->with('success',__('Business clone was successful'));
		}catch (\Exception $exception){
			$clone->delete();
			return redirect()->back()->with('warning',__($exception->getMessage()));
		}
	}
}
