<?php
namespace Modules\Art\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Art\Models\Art;
use Modules\Art\Models\ArtTerm;
use Modules\Art\Models\ArtTranslation;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;
use Modules\Location\Models\LocationCategory;
use Modules\User\Models\Plan;
use App\Models\RefIpanorama;
use App\Models\RefRelationIpanorama;
use Modules\Art\Models\ArtCategory;

class VendorArtController extends FrontendController
{
    protected $artClass;
    protected $artTranslationClass;
    protected $artTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    protected $artCategoryClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct()
    {
        parent::__construct();
        $this->artClass = Art::class;
        $this->artTranslationClass = ArtTranslation::class;
        $this->artTermClass = ArtTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->bookingClass = Booking::class;
        $this->artCategoryClass = ArtCategory::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Art::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function indexArt(Request $request)
    {
        $this->checkPermission('art_view');
        $user_id = Auth::id();
        $list_tour = $this->artClass::where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'breadcrumbs'        => [
                [
                    'name' => __('listing.art.manage'),
                    'url'  => route('art.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __('listing.art.manage'),
        ];
        return view('Art::frontend.vendorArt.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('art_view');
        $user_id = Auth::id();
        $list_tour = $this->artClass::onlyTrashed()->where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('listing.art.manage'),
                    'url'  => route('art.vendor.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Recovery Arts"),
        ];
        return view('Art::frontend.vendorArt.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('art_delete');
        $user_id = Auth::id();
        $query = $this->artClass::onlyTrashed()->where("author_id", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
        }
        return redirect(route('art.vendor.recovery'))->with('success', __('Restore art success!'));
    }

    public function createArt(Request $request)
    {
        $this->checkPermission('art_create');
        $row = new $this->artClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->artTranslationClass(),
            'art_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'art_category'     => $this->artCategoryClass::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes'    => $this->attributesClass::where('service', 'art')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('listing.art.manage'),
                    'url'  => route('art.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Arts"),
        ];
        return view('Art::frontend.vendorArt.detail', $data);
    }


    public function store( Request $request, $id ){
        if($id>0){
            $this->checkPermission('art_update');
            $row = $this->artClass::find($id);
            if (empty($row)) {
                return redirect(route('art.vendor.index'));
            }

            if($row->author_id != Auth::id() and !$this->hasPermission('art_manage_others'))
            {
                return redirect(route('art.vendor.index'));
            }
        }else{
            $this->checkPermission('art_create');
            $row = new $this->artClass();
            $row->status = "publish";
            if(setting_item("art_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
            $row->author_id = Auth::id();
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'duration',
            'start_time',
            'price',
            'sale_price',
            'ticket_types',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'surrounding',
            'room',
            'bed',
            'bathroom',
            'square',
            'engineering',
            'software',
            'phone',
            'website',
            'ipanorama_id',
        ];

        $row->fillByAttr($dataKeys,$request->input());

        if(!auth()->user()->checkUserPlan() and $row->status == "publish") {
            return redirect(route('user.plan'));
        }

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if($id > 0 ){
                event(new UpdatedServiceEvent($row));

                $ipanoramaInp = RefRelationIpanorama::where('slug', '=', $row->slug)->first();

                if ($ipanoramaInp) {
                    $ipanoramaInp->id_ipanorama = $request->input('div-ipanorama');
                    $ipanoramaInp->save();
                } else {
                    $ipanoramaInpNew = new RefRelationIpanorama();
                    $ipanoramaInpNew->id_ipanorama = $request->input('div-ipanorama');
                    $ipanoramaInpNew->slug = $row->slug;
                    $ipanoramaInpNew->save();
                }

                return back()->with('success',  __('Art updated') );
            }else{
                event(new CreatedServicesEvent($row));

                $ipanoramaInp = new RefRelationIpanorama();
                $ipanoramaInp->id_ipanorama = $request->input('div-ipanorama');
                $ipanoramaInp->slug = $row->slug;
                $ipanoramaInp->save();

                return redirect(route('art.vendor.edit',['id'=>$row->id]))->with('success', __('Art created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->artTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->artTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->artTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function editArt(Request $request, $id)
    {
        $this->checkPermission('art_update');
        $user_id = Auth::id();
        $row = $this->artClass::where("author_id", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('art.vendor.index'))->with('warning', __('Art not found!'));
        }
        $translation = $row->translate($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'art_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'art_category'     => $this->artCategoryClass::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes'    => $this->attributesClass::where('service', 'art')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('listing.art.manage'),
                    'url'  => route('art.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Arts"),
        ];
        return view('Art::frontend.vendorArt.detail', $data);
    }

    public function deleteArt($id)
    {
        $this->checkPermission('art_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->artClass::where("author_id", $user_id)->where("id", $id)->withTrahsed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->artClass::where("author_id", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
                event(new UpdatedServiceEvent($query));
            }
        }
        return redirect(route('art.vendor.index'))->with('success', __('Delete art success!'));
    }

    public function bulkEditArt($id , Request $request){
        $this->checkPermission('art_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->artClass::where("author_id", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                if(!auth()->user()->checkUserPlan()) {
                    return redirect(route('user.plan'));
                }
                break;
            case 'make-private':
                $query->status = 'private';
                break;
        }
        $query->save();
        event(new UpdatedServiceEvent($query));

        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("art_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();

                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}
