<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 7/30/2019
 * Time: 1:56 PM
 */
namespace Modules\Business\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;
use Modules\Location\Models\LocationCategory;
use Modules\Business\Models\Business;
use Modules\Business\Models\BusinessTerm;
use Modules\Business\Models\BusinessTranslation;
use Modules\Business\Models\BusinessCategory;

class BusinessController extends AdminController
{
    protected $business;
    protected $business_translation;
    protected $business_term;
    protected $attributes;
    protected $location;
    protected $businessCategoryClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct()
    {
        $this->setActiveMenu(route('business.admin.index'));
        $this->business = Business::class;
        $this->business_translation = BusinessTranslation::class;
        $this->business_term = BusinessTerm::class;
        $this->attributes = Attributes::class;
        $this->location = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->businessCategoryClass = BusinessCategory::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Business::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('business_view');
        $query = $this->business::query() ;
        $query->orderBy('id', 'desc');
        if (!empty($business_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $business_name . '%');
            $query->orderBy('title', 'asc');
        }
        if (!empty($is_featured = $request->input('is_featured'))) {
            $query->where('is_featured', 1);
        }
        if (!empty($location_id = $request->query('location_id'))) {
            $query->where('location_id', $location_id);
        }
        if ($this->hasPermission('business_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('create_user', $author);
            }
        } else {
            $query->where('create_user', Auth::id());
        }
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'business_manage_others' => $this->hasPermission('business_manage_others'),
            'breadcrumbs'        => [
                [
                    'name' => __('Businesss'),
                    'url'  => route('business.admin.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Business Management")
        ];
        return view('Business::admin.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('business_view');
        $query = $this->business::onlyTrashed() ;
        $query->orderBy('id', 'desc');
        if (!empty($business_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $business_name . '%');
            $query->orderBy('title', 'asc');
        }

        if ($this->hasPermission('business_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('create_user', $author);
            }
        } else {
            $query->where('create_user', Auth::id());
        }
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'business_manage_others' => $this->hasPermission('business_manage_others'),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('Businesss'),
                    'url'  => route('business.admin.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Recovery Business Management")
        ];
        return view('Business::admin.index', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('business_create');
        $row = new $this->business();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'            => $row,
            'attributes'     => $this->attributes::where('service', 'business')->get(),
            'business_category' => $this->businessCategoryClass::where('status', 'publish')->get()->toTree(),
            'business_location' => $this->location::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'translation'    => new $this->business_translation(),
            'breadcrumbs'    => [
                [
                    'name' => __('Businesss'),
                    'url'  => route('business.admin.index')
                ],
                [
                    'name'  => __('Add Business'),
                    'class' => 'active'
                ],
            ],
            'page_title'     => __("Add new Business"),
        ];

        return view('Business::admin.detail', $data);
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('business_update');
        $row = $this->business::find($id);
        if (empty($row)) {
            return redirect(route('business.admin.index'));
        }
        $translation = $row->translate($request->query('lang',get_main_lang()));
        if (!$this->hasPermission('business_manage_others')) {
            if ($row->author_id != Auth::id()) {
                return redirect(route('business.admin.index'));
            }
        }
        $data = [
            'row'            => $row,
            'translation'    => $translation,
            "selected_terms" => $row->terms->pluck('term_id'),
            'attributes'     => $this->attributes::where('service', 'business')->get(),
            'business_category'  => $this->businessCategoryClass::where('status', 'publish')->get()->toTree(),
            'business_location'  => $this->location::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'enable_multi_lang'=>true,
            'breadcrumbs'    => [
                [
                    'name' => __('Businesss'),
                    'url'  => route('business.admin.index')
                ],
                [
                    'name'  => __('Edit Business'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Edit: :name",['name'=>$row->title]),
        ];

        return view('Business::admin.detail', $data);
    }

    public function store( Request $request, $id ){

        if($id>0){
            $this->checkPermission('business_update');
            $row = $this->business::find($id);
            if (empty($row)) {
                return redirect(route('business.admin.index'));
            }

            if($row->author_id != Auth::id() and !$this->hasPermission('business_manage_others'))
            {
                return redirect(route('business.admin.index'));
            }
        }else{
            $this->checkPermission('business_create');
            $row = new $this->business();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'status',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'category_id',
            'gallery',
            'bed',
            'bathroom',
            'square',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'price',
            'sale_price',
            'max_guests',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'min_day_before_booking',
            'min_day_stays',
            'surrounding',
            'franchising',
            'phone',
            'website',
            'ipanorama_id',

        ];
        if($this->hasPermission('business_manage_others')){
            $dataKeys[] = 'author_id';
        }

        $row->fillByAttr($dataKeys,$request->input());
        if($request->input('slug')){
            $row->slug = $request->input('slug');
        }
	    $row->ical_import_url  = $request->ical_import_url;
        $row->enable_service_fee = $request->input('enable_service_fee');
        $row->service_fee = $request->input('service_fee');

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if($id > 0 ){
                event(new UpdatedServiceEvent($row));
                return back()->with('success',  __('Business updated') );
            }else{
                event(new CreatedServicesEvent($row));
                return redirect(route('business.admin.edit',$row->id))->with('success', __('Business created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('business_manage_attributes');
        if (empty($request->input('terms'))) {
            $this->business_term::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->business_term::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->business_term::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function bulkEdit(Request $request)
    {

        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }

        switch ($action){
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->business::where("id", $id);
                    if (!$this->hasPermission('business_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('business_delete');
                    }
                    $row  =  $query->first();
                    if(!empty($row)){
                        $row->delete();
                        event(new UpdatedServiceEvent($row));

                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "permanently_delete":
                foreach ($ids as $id) {
                    $query = $this->business::where("id", $id);
                    if (!$this->hasPermission('business_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('business_delete');
                    }
                    $row  =  $query->withTrashed()->first();
                    if($row){
                        $row->forceDelete();
                    }
                }
                return redirect()->back()->with('success', __('Permanently delete success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->business::withTrashed()->where("id", $id);
                    if (!$this->hasPermission('business_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('business_delete');
                    }
                    $row = $query->first();
                    if(!empty($row)){
                        $row->restore();
                        event(new UpdatedServiceEvent($row));

                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('business_create');
                foreach ($ids as $id) {
                    (new $this->business())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->business::where("id", $id);
                    if (!$this->hasPermission('business_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('business_update');
                    }
                    $row = $query->first();
                    $row->status  = $action;
                    $row->save();
                        event(new UpdatedServiceEvent($row));
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }


    }

    public function getForSelect2(Request $request)
    {
        $pre_selected = $request->query('pre_selected');
        $selected = $request->query('selected');
        if ($pre_selected && $selected) {
            if (is_array($selected)) {
                $items = $this->business::select('id', 'title as text')->whereIn('id', $selected)->take(50)->get();
                return $this->sendSuccess([
                    'items' => $items
                ]);
            } else {
                $item = $this->business::find($selected);
            }
            if (empty($item)) {
                return $this->sendSuccess([
                    'text' => ''
                ]);
            } else {
                return $this->sendSuccess([
                    'text' => $item->name
                ]);
            }
        }
        $q = $request->query('q');
        $query = $this->business::select('id', 'title as text')->where("status", "publish");
        if ($q) {
            $query->where('title', 'like', '%' . $q . '%');
        }
        $res = $query->orderBy('id', 'desc')->limit(20)->get();
        return $this->sendSuccess([
            'results' => $res
        ]);
    }
}
